### ISSUE TITLE
not sending to bot

### ISSUE THREAD

**Issue by W8CODE** [zile42O/browser-stealer#1]
the script runs perfectly, it gets all the info, stores in txt file, but then it deletes all, but the zip isnt getting sent? i have input bot_token and chat id as a t.me link as well as just @username, but its not sending the stuff? there also are no errors given. pls help??

**Comment by zile42O** [comment]
Did you try with run as administrator permissions? (If is it windows OS)

**Comment by W8CODE** [comment]
no bro i im running using python in windows. i dm u in telegram lets chat there :)
